import { ThemeSizes } from '../globals/Theme'

export type PresetValue = 
  | 'custom'
  | 'bardahl'
  | 'ocean-breeze'
  | 'midnight-violet'
  | 'autumn-warmth'
  | 'nature'
  | 'corporate-clarity'
  | 'elegant-slate'
  | 'tech-indigo'
  | 'candy-pop'
  | 'sunset-vibes'
  | 'luxinnovation'

export type ThemeColors = {
  background: string
  foreground: string
  card: string
  cardForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  destructive: string
  border: string
  input: string
  ring: string
  chart1: string
  chart2: string
  chart3: string
  chart4: string
  chart5: string
  sidebar: string
  sidebarForeground: string
  sidebarPrimary: string
  sidebarPrimaryForeground: string
  sidebarAccent: string
  sidebarAccentForeground: string
  sidebarBorder: string
  sidebarRing: string
}

export type ThemePreset = {
  id: string
  name: string
  colors: {
    light: ThemeColors
    dark: ThemeColors
  }
  sizes: ThemeSizes
}

export const themePresets: ThemePreset[] = [
  {
    id: 'bardahl',
    name: 'Bardahl',
    colors: {
      light: {
        background: '#ffffff',
        foreground: '#202020',
        card: '#ffffff',
        cardForeground: '#202020',
        popover: '#ffffff',
        popoverForeground: '#202020',
        primary: '#f9d22f',
        primaryForeground: '#202020',
        secondary: '#202020',
        secondaryForeground: '#ffffff',
        muted: '#f4f4f4',
        mutedForeground: '#666666',
        accent: '#f9d22f',
        accentForeground: '#202020',
        destructive: '#dc2626',
        border: '#e5e5e5',
        input: '#f4f4f4',
        ring: '#f9d22f',
        chart1: '#f9d22f',
        chart2: '#202020',
        chart3: '#666666',
        chart4: '#999999',
        chart5: '#cccccc',
        sidebar: '#202020',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#f9d22f',
        sidebarPrimaryForeground: '#202020',
        sidebarAccent: '#f9d22f',
        sidebarAccentForeground: '#202020',
        sidebarBorder: '#404040',
        sidebarRing: '#f9d22f',
      },
      dark: {
        background: '#202020',
        foreground: '#ffffff',
        card: '#2b2b2b',
        cardForeground: '#ffffff',
        popover: '#2b2b2b',
        popoverForeground: '#ffffff',
        primary: '#f9d22f',
        primaryForeground: '#202020',
        secondary: '#ffffff',
        secondaryForeground: '#202020',
        muted: '#2b2b2b',
        mutedForeground: '#a1a1a1',
        accent: '#f9d22f',
        accentForeground: '#202020',
        destructive: '#dc2626',
        border: '#404040',
        input: '#2b2b2b',
        ring: '#f9d22f',
        chart1: '#f9d22f',
        chart2: '#ffffff',
        chart3: '#a1a1a1',
        chart4: '#808080',
        chart5: '#666666',
        sidebar: '#2b2b2b',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#f9d22f',
        sidebarPrimaryForeground: '#202020',
        sidebarAccent: '#f9d22f',
        sidebarAccentForeground: '#202020',
        sidebarBorder: '#404040',
        sidebarRing: '#f9d22f',
      }
    },
    sizes: {
      radius: '0.25rem',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    colors: {
      light: {
        background: '#f0f4f8',
        foreground: '#1e293b',
        card: '#ffffff',
        cardForeground: '#1e293b',
        popover: '#ffffff',
        popoverForeground: '#1e293b',
        primary: '#0ea5e9',
        primaryForeground: '#ffffff',
        secondary: '#e0f2fe',
        secondaryForeground: '#0c4a6e',
        muted: '#e0f2fe',
        mutedForeground: '#64748b',
        accent: '#0284c7',
        accentForeground: '#ffffff',
        destructive: '#ef4444',
        border: '#bae6fd',
        input: '#e0f2fe',
        ring: '#0ea5e9',
        chart1: '#0ea5e9',
        chart2: '#0c4a6e',
        chart3: '#64748b',
        chart4: '#64748b',
        chart5: '#64748b',
        sidebar: '#0c4a6e',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#0ea5e9',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#0ea5e9',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#0ea5e9',
      },
      dark: {
        background: '#0c4a6e',
        foreground: '#f0f9ff',
        card: '#075985',
        cardForeground: '#f0f9ff',
        popover: '#075985',
        popoverForeground: '#f0f9ff',
        primary: '#38bdf8',
        primaryForeground: '#0c4a6e',
        secondary: '#0369a1',
        secondaryForeground: '#f0f9ff',
        muted: '#0369a1',
        mutedForeground: '#7dd3fc',
        accent: '#38bdf8',
        accentForeground: '#0c4a6e',
        destructive: '#ef4444',
        border: '#0369a1',
        input: '#0369a1',
        ring: '#38bdf8',
        chart1: '#0ea5e9',
        chart2: '#0c4a6e',
        chart3: '#64748b',
        chart4: '#64748b',
        chart5: '#64748b',
        sidebar: '#0c4a6e',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#0ea5e9',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#0ea5e9',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#0ea5e9',
      }
    },
    sizes: {
      radius: '0.5rem',
    },
  },
  {
    id: 'midnight-violet',
    name: 'Midnight Violet',
    colors: {
      light: {
        background: '#faf5ff',
        foreground: '#1e1b4b',
        card: '#ffffff',
        cardForeground: '#1e1b4b',
        popover: '#ffffff',
        popoverForeground: '#1e1b4b',
        primary: '#8b5cf6',
        primaryForeground: '#ffffff',
        secondary: '#f3e8ff',
        secondaryForeground: '#5b21b6',
        muted: '#f3e8ff',
        mutedForeground: '#6d28d9',
        accent: '#7c3aed',
        accentForeground: '#ffffff',
        destructive: '#ef4444',
        border: '#e9d5ff',
        input: '#f3e8ff',
        ring: '#8b5cf6',
        chart1: '#8b5cf6',
        chart2: '#5b21b6',
        chart3: '#6d28d9',
        chart4: '#6d28d9',
        chart5: '#6d28d9',
        sidebar: '#5b21b6',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#8b5cf6',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#8b5cf6',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#8b5cf6',
      },
      dark: {
        background: '#2e1065',
        foreground: '#faf5ff',
        card: '#4c1d95',
        cardForeground: '#faf5ff',
        popover: '#4c1d95',
        popoverForeground: '#faf5ff',
        primary: '#a855f7',
        primaryForeground: '#ffffff',
        secondary: '#5b21b6',
        secondaryForeground: '#faf5ff',
        muted: '#5b21b6',
        mutedForeground: '#d8b4fe',
        accent: '#a855f7',
        accentForeground: '#ffffff',
        destructive: '#ef4444',
        border: '#6d28d9',
        input: '#5b21b6',
        ring: '#a855f7',
        chart1: '#8b5cf6',
        chart2: '#5b21b6',
        chart3: '#6d28d9',
        chart4: '#6d28d9',
        chart5: '#6d28d9',
        sidebar: '#5b21b6',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#8b5cf6',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#8b5cf6',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#8b5cf6',
      }
    },
    sizes: {
      radius: '0.75rem',
    },
  },
  {
    id: 'autumn-warmth',
    name: 'Autumn Warmth',
    colors: {
      light: {
        background: '#fffbeb',
        foreground: '#451a03',
        card: '#ffffff',
        cardForeground: '#451a03',
        popover: '#ffffff',
        popoverForeground: '#451a03',
        primary: '#d97706',
        primaryForeground: '#ffffff',
        secondary: '#fef3c7',
        secondaryForeground: '#92400e',
        muted: '#fef3c7',
        mutedForeground: '#b45309',
        accent: '#f59e0b',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        border: '#fde68a',
        input: '#fef3c7',
        ring: '#d97706',
        chart1: '#d97706',
        chart2: '#92400e',
        chart3: '#b45309',
        chart4: '#b45309',
        chart5: '#b45309',
        sidebar: '#92400e',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#d97706',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#d97706',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#d97706',
      },
      dark: {
        background: '#451a03',
        foreground: '#fffbeb',
        card: '#7c2d12',
        cardForeground: '#fffbeb',
        popover: '#7c2d12',
        popoverForeground: '#fffbeb',
        primary: '#f59e0b',
        primaryForeground: '#451a03',
        secondary: '#92400e',
        secondaryForeground: '#fffbeb',
        muted: '#92400e',
        mutedForeground: '#fcd34d',
        accent: '#f59e0b',
        accentForeground: '#451a03',
        destructive: '#dc2626',
        border: '#b45309',
        input: '#92400e',
        ring: '#f59e0b',
        chart1: '#d97706',
        chart2: '#92400e',
        chart3: '#b45309',
        chart4: '#b45309',
        chart5: '#b45309',
        sidebar: '#92400e',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#d97706',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#d97706',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#d97706',
      }
    },
    sizes: {
      radius: '0.375rem',
    },
  },
  {
    id: 'nature',
    name: 'Nature',
    colors: {
      light: {
        background: '#f8faf7',
        foreground: '#2c392f',
        card: '#ffffff',
        cardForeground: '#2c392f',
        popover: '#ffffff',
        popoverForeground: '#2c392f',
        primary: '#4a6741',
        primaryForeground: '#ffffff',
        secondary: '#e9efe7',
        secondaryForeground: '#2c392f',
        muted: '#e9efe7',
        mutedForeground: '#5c7355',
        accent: '#e9efe7',
        accentForeground: '#2c392f',
        destructive: '#cc4444',
        border: '#d8e2d5',
        input: '#d8e2d5',
        ring: '#4a6741',
        chart1: '#4a6741',
        chart2: '#2c392f',
        chart3: '#5c7355',
        chart4: '#5c7355',
        chart5: '#5c7355',
        sidebar: '#2c392f',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#4a6741',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#4a6741',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#4a6741',
      },
      dark: {
        background: '#1c2419',
        foreground: '#e9efea',
        card: '#2c392f',
        cardForeground: '#e9efea',
        popover: '#2c392f',
        popoverForeground: '#e9efea',
        primary: '#7c9a73',
        primaryForeground: '#ffffff',
        secondary: '#3a483d',
        secondaryForeground: '#e9efea',
        muted: '#3a483d',
        mutedForeground: '#a5b6a0',
        accent: '#3a483d',
        accentForeground: '#e9efea',
        destructive: '#cc4444',
        border: '#3a483d',
        input: '#3a483d',
        ring: '#7c9a73',
        chart1: '#4a6741',
        chart2: '#2c392f',
        chart3: '#5c7355',
        chart4: '#5c7355',
        chart5: '#5c7355',
        sidebar: '#2c392f', 
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#4a6741',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#4a6741',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#4a6741',
      }
    },
    sizes: {
      radius: '0.375rem',
    },
  },
  {
    id: 'corporate-clarity',
    name: 'Corporate Clarity',
    colors: {
      light: {
        background: '#f8fafc',
        foreground: '#0f172a',
        card: '#ffffff',
        cardForeground: '#0f172a',
        popover: '#ffffff',
        popoverForeground: '#0f172a',
        primary: '#0f766e',
        primaryForeground: '#ffffff',
        secondary: '#f1f5f9',
        secondaryForeground: '#0f172a',
        muted: '#f1f5f9',
        mutedForeground: '#475569',
        accent: '#0d9488',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        border: '#e2e8f0',
        input: '#f1f5f9',
        ring: '#0f766e',
        chart1: '#0f766e',
        chart2: '#0f172a',
        chart3: '#475569',
        chart4: '#475569',
        chart5: '#475569',
        sidebar: '#0f172a', 
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#0f766e',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#0f766e',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#0f766e',
      },
      dark: {
        background: '#0f172a',
        foreground: '#f8fafc',
        card: '#1e293b',
        cardForeground: '#f8fafc',
        popover: '#1e293b',
        popoverForeground: '#f8fafc',
        primary: '#14b8a6',
        primaryForeground: '#0f172a',
        secondary: '#1e293b',
        secondaryForeground: '#f8fafc',
        muted: '#1e293b',
        mutedForeground: '#94a3b8',
        accent: '#14b8a6',
        accentForeground: '#0f172a',
        destructive: '#dc2626',
        border: '#334155',
        input: '#1e293b',
        ring: '#14b8a6',
        chart1: '#0f766e',
        chart2: '#0f172a',
        chart3: '#475569',
        chart4: '#475569',
        chart5: '#475569',
        sidebar: '#0f172a', 
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#0f766e',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#0f766e',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#0f766e',
      }
    },
    sizes: {
      radius: '0.25rem',
    },
  },
  {
    id: 'elegant-slate',
    name: 'Elegant Slate',
    colors: {
      light: {
        background: '#ffffff',
        foreground: '#1c1917',
        card: '#fafaf9',
        cardForeground: '#1c1917',
        popover: '#fafaf9',
        popoverForeground: '#1c1917',
        primary: '#44403c',
        primaryForeground: '#fafaf9',
        secondary: '#f5f5f4',
        secondaryForeground: '#1c1917',
        muted: '#f5f5f4',
        mutedForeground: '#78716c',
        accent: '#57534e',
        accentForeground: '#fafaf9',
        destructive: '#dc2626',
        border: '#e7e5e4',
        input: '#f5f5f4',
        ring: '#44403c',
        chart1: '#44403c',
        chart2: '#1c1917',
        chart3: '#78716c',
        chart4: '#78716c',
        chart5: '#78716c',  
        sidebar: '#1c1917',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#44403c',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#44403c',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#44403c',
      },
      dark: {
        background: '#1c1917',
        foreground: '#fafaf9',
        card: '#292524',
        cardForeground: '#fafaf9',
        popover: '#292524',
        popoverForeground: '#fafaf9',
        primary: '#d6d3d1',
        primaryForeground: '#1c1917',
        secondary: '#292524',
        secondaryForeground: '#fafaf9',
        muted: '#292524',
        mutedForeground: '#a8a29e',
        accent: '#d6d3d1',
        accentForeground: '#1c1917',
        destructive: '#dc2626',
        border: '#44403c',
        input: '#292524',
        ring: '#d6d3d1',
        chart1: '#44403c',
        chart2: '#1c1917',
        chart3: '#78716c',
        chart4: '#78716c',
        chart5: '#78716c',
        sidebar: '#1c1917', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#44403c',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#44403c',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#44403c',
      }
    },
    sizes: {
      radius: '0.125rem',
    },
  },
  {
    id: 'tech-indigo',
    name: 'Tech Indigo',
    colors: {
      light: {
        background: '#f8fafc',
        foreground: '#020617',
        card: '#ffffff',
        cardForeground: '#020617',
        popover: '#ffffff',
        popoverForeground: '#020617',
        primary: '#3730a3',
        primaryForeground: '#ffffff',
        secondary: '#f1f5f9',
        secondaryForeground: '#020617',
        muted: '#f1f5f9',
        mutedForeground: '#475569',
        accent: '#4f46e5',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        border: '#e2e8f0',
        input: '#f1f5f9',
        ring: '#3730a3',
        chart1: '#3730a3',
        chart2: '#020617',
        chart3: '#475569',
        chart4: '#475569',
        chart5: '#475569',
        sidebar: '#020617', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#3730a3',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#3730a3',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#3730a3',
      },
      dark: {
        background: '#020617',
        foreground: '#f8fafc',
        card: '#0f172a',
        cardForeground: '#f8fafc',
        popover: '#0f172a',
        popoverForeground: '#f8fafc',
        primary: '#6366f1',
        primaryForeground: '#020617',
        secondary: '#0f172a',
        secondaryForeground: '#f8fafc',
        muted: '#0f172a',
        mutedForeground: '#94a3b8',
        accent: '#6366f1',
        accentForeground: '#020617',
        destructive: '#dc2626',
        border: '#1e293b',
        input: '#0f172a',
        ring: '#6366f1',
        chart1: '#3730a3',
        chart2: '#020617',
        chart3: '#475569',
        chart4: '#475569',
        chart5: '#475569',
        sidebar: '#020617', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#3730a3',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#3730a3',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#3730a3',
      }
    },
    sizes: {
      radius: '0.375rem',
    },
  },
  {
    id: 'candy-pop',
    name: 'Candy Pop',
    colors: {
      light: {
        background: '#fdf4ff',
        foreground: '#581c87',
        card: '#ffffff',
        cardForeground: '#581c87',
        popover: '#ffffff',
        popoverForeground: '#581c87',
        primary: '#d946ef',
        primaryForeground: '#ffffff',
        secondary: '#fae8ff',
        secondaryForeground: '#581c87',
        muted: '#fae8ff',
        mutedForeground: '#9d174d',
        accent: '#e879f9',
        accentForeground: '#ffffff',
        destructive: '#e11d48',
        border: '#fae8ff',
        input: '#fae8ff',
        ring: '#d946ef',    
        chart1: '#d946ef',
        chart2: '#581c87',
        chart3: '#9d174d',
        chart4: '#9d174d',
        chart5: '#9d174d',
        sidebar: '#581c87', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#d946ef',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#d946ef',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#d946ef',
      },
      dark: {
        background: '#581c87',
        foreground: '#fdf4ff',
        card: '#701a75',
        cardForeground: '#fdf4ff',
        popover: '#701a75',
        popoverForeground: '#fdf4ff',
        primary: '#f0abfc',
        primaryForeground: '#581c87',
        secondary: '#701a75',
        secondaryForeground: '#fdf4ff',
        muted: '#701a75',
        mutedForeground: '#f5d0fe',
        accent: '#f0abfc',
        accentForeground: '#581c87',
        destructive: '#e11d48',
        border: '#86198f',
        input: '#701a75',
        ring: '#f0abfc',    
        chart1: '#d946ef',
        chart2: '#581c87',
        chart3: '#9d174d',
        chart4: '#9d174d',
        chart5: '#9d174d',
        sidebar: '#581c87', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#d946ef',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#d946ef',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#d946ef',
      }
    },
    sizes: {
      radius: '1rem',
    },
  },
  {
    id: 'sunset-vibes',
    name: 'Sunset Vibes',
    colors: {
      light: {
        background: '#fff7ed',
        foreground: '#7c2d12',
        card: '#ffffff',
        cardForeground: '#7c2d12',
        popover: '#ffffff',
        popoverForeground: '#7c2d12',
        primary: '#ea580c',
        primaryForeground: '#ffffff',
        secondary: '#ffedd5',
        secondaryForeground: '#7c2d12',
        muted: '#ffedd5',
        mutedForeground: '#9a3412',
        accent: '#fb923c',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        border: '#fed7aa',
        input: '#ffedd5',
        ring: '#ea580c',    
        chart1: '#ea580c',
        chart2: '#7c2d12',
        chart3: '#9a3412',
        chart4: '#9a3412',
        chart5: '#9a3412',
        sidebar: '#7c2d12', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#ea580c',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#ea580c',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#ea580c',
      },
      dark: {
        background: '#7c2d12',
        foreground: '#fff7ed',
        card: '#9a3412',
        cardForeground: '#fff7ed',
        popover: '#9a3412',
        popoverForeground: '#fff7ed',
        primary: '#fb923c',
        primaryForeground: '#7c2d12',
        secondary: '#9a3412',
        secondaryForeground: '#fff7ed',
        muted: '#9a3412',
        mutedForeground: '#fed7aa',
        accent: '#fb923c',
        accentForeground: '#7c2d12',
        destructive: '#dc2626',
        border: '#c2410c',
        input: '#9a3412',
        ring: '#fb923c',    
        chart1: '#ea580c',
        chart2: '#7c2d12',
        chart3: '#9a3412',
        chart4: '#9a3412',
        chart5: '#9a3412',
        sidebar: '#7c2d12', 
        sidebarForeground: '#ffffff',   
        sidebarPrimary: '#ea580c',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#ea580c',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#404040',
        sidebarRing: '#ea580c',
      }
    },
    sizes: {
      radius: '0.75rem',
    },
  },
  {
    id: 'luxinnovation',
    name: 'Luxinnovation',
    colors: {
      light: {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        cardForeground: '#333333',
        popover: '#ffffff',
        popoverForeground: '#333333',
        primary: '#4097fc',
        primaryForeground: '#ffffff',
        secondary: '#21214d',
        secondaryForeground: '#ffffff',
        muted: '#f5f5f5',
        mutedForeground: '#666666',
        accent: '#4097fc',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        border: '#e5e5e5',
        input: '#f5f5f5',
        ring: '#4097fc',
        chart1: '#4097fc',
        chart2: '#21214d',
        chart3: '#6eb4fd',
        chart4: '#9cccfd',
        chart5: '#cae3fe',
        sidebar: '#21214d',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#4097fc',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#4097fc',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#3f3f73',
        sidebarRing: '#4097fc',
      },
      dark: {
        background: '#21214d',
        foreground: '#ffffff',
        card: '#2a2a5c',
        cardForeground: '#ffffff',
        popover: '#2a2a5c',
        popoverForeground: '#ffffff',
        primary: '#4097fc',
        primaryForeground: '#ffffff',
        secondary: '#ffffff',
        secondaryForeground: '#21214d',
        muted: '#2a2a5c',
        mutedForeground: '#a1a1aa',
        accent: '#4097fc',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        border: '#3f3f73',
        input: '#2a2a5c',
        ring: '#4097fc',
        chart1: '#4097fc',
        chart2: '#ffffff',
        chart3: '#6eb4fd',
        chart4: '#9cccfd',
        chart5: '#cae3fe',
        sidebar: '#2a2a5c',
        sidebarForeground: '#ffffff',
        sidebarPrimary: '#4097fc',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#4097fc',
        sidebarAccentForeground: '#ffffff',
        sidebarBorder: '#3f3f73',
        sidebarRing: '#4097fc',
      }
    },
    sizes: {
      radius: '0.375rem',
    },
  },
]

export const getPresetById = (id: string): ThemePreset | undefined => {
  return themePresets.find((preset) => preset.id === id)
} 